//DO NOT MODIFY THIS FILE
//Instead, override the this[] indexer in your entity base class
using System;
using AppFramework.AppClasses;
namespace FirstAppFrameworkApplicationEntities.EntityClasses
{
    partial class CompanyDetails
    {
        [System.ComponentModel.DataAnnotations.Display(Name = "Address", Order = 0)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Address")]
        [System.ComponentModel.DataAnnotations.DataType(System.ComponentModel.DataAnnotations.DataType.MultilineText)]
        [System.ComponentModel.DataAnnotations.Editable(true, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String CompanyAddress
        {
            get
            {
                return this.getString("CompanyAddress");
            }
            set
            {
                this["CompanyAddress"] = value;
            }
        }

    }
}
