//DO NOT MODIFY THIS FILE
//Instead, override the this[] indexer in your entity base class
using System;
using AppFramework.AppClasses;
namespace FirstAppFrameworkApplicationEntities.EntityClasses
{
    partial class Customers
    {
        [System.ComponentModel.DataAnnotations.Display(Name = "Customer ID", Order = 0)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Customer ID")]
        [System.ComponentModel.DataAnnotations.Editable(false, AllowInitialValue = false)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String CustomerID
        {
            get
            {
                return this.getString("CustomerID");
            }
            set
            {
                this["CustomerID"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Name", Order = 1)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Name")]
        [System.ComponentModel.DataAnnotations.Editable(true, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String Name
        {
            get
            {
                return this.getString("Name");
            }
            set
            {
                this["Name"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Money", Order = 2)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Money")]
        [System.ComponentModel.DataAnnotations.Editable(true, AllowInitialValue = false)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual decimal Money
        {
            get
            {
                return this.getReal("Money");
            }
            set
            {
                this["Money"] = value;
            }
        }

    }
}
