//DO NOT MODIFY THIS FILE
//Instead, override the this[] indexer in your entity base class
using System;
using AppFramework.AppClasses;
namespace FirstAppFrameworkApplicationEntities.EntityClasses
{
    partial class InvoiceDetails
    {
        [System.ComponentModel.DataAnnotations.Display(Name = "Invoice ID", Order = 0)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Invoice ID")]
        [System.ComponentModel.DataAnnotations.Editable(true, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String InvoiceID
        {
            get
            {
                return this.getString("InvoiceID");
            }
            set
            {
                this["InvoiceID"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Description", Order = 1)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Description")]
        [System.ComponentModel.DataAnnotations.Editable(true, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String Description
        {
            get
            {
                return this.getString("Description");
            }
            set
            {
                this["Description"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Quantity", Order = 2)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Quantity")]
        [System.ComponentModel.DataAnnotations.Editable(false, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual int Quantity
        {
            get
            {
                return this.getInteger("Quantity");
            }
            set
            {
                this["Quantity"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Unit Price", Order = 3)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Unit Price")]
        [System.ComponentModel.DataAnnotations.Editable(false, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual decimal UnitPrice
        {
            get
            {
                return this.getReal("UnitPrice");
            }
            set
            {
                this["UnitPrice"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Amount", Order = 4)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Amount")]
        [System.ComponentModel.DataAnnotations.Editable(false, AllowInitialValue = false)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual decimal Amount
        {
            get
            {
                return this.getReal("Amount");
            }
            set
            {
                this["Amount"] = value;
            }
        }

    }
}
