//DO NOT MODIFY THIS FILE
//Instead, override the this[] indexer in your entity base class
using System;
using AppFramework.AppClasses;
namespace FirstAppFrameworkApplicationEntities.EntityClasses
{
    partial class Invoices
    {
        [System.ComponentModel.DataAnnotations.Display(Name = "Invoice ID", Order = 0)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Invoice ID")]
        [System.ComponentModel.DataAnnotations.Editable(true, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String InvoiceID
        {
            get
            {
                return this.getString("InvoiceID");
            }
            set
            {
                this["InvoiceID"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Customer", Order = 1)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Customer")]
        [System.ComponentModel.DataAnnotations.Editable(true, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String CustomerID
        {
            get
            {
                return this.getString("CustomerID");
            }
            set
            {
                this["CustomerID"] = value;
            }
        }

    }
}
