//DO NOT MODIFY THIS FILE
//Instead, override the this[] indexer in your entity base class
using System;
using AppFramework.AppClasses;
namespace FirstAppFrameworkApplicationEntities.EntityClasses
{
    partial class Items
    {
        [System.ComponentModel.DataAnnotations.Display(Name = "Item", Order = 0)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Item")]
        [System.ComponentModel.DataAnnotations.Editable(false, AllowInitialValue = false)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String ItemID
        {
            get
            {
                return this.getString("ItemID");
            }
            set
            {
                this["ItemID"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Item Name", Order = 1)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Item Name")]
        [System.ComponentModel.DataAnnotations.Editable(true, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String ItemName
        {
            get
            {
                return this.getString("ItemName");
            }
            set
            {
                this["ItemName"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Description", Order = 2)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Description")]
        [System.ComponentModel.DataAnnotations.Editable(true, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String ItemDescription
        {
            get
            {
                return this.getString("ItemDescription");
            }
            set
            {
                this["ItemDescription"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Quantity", Order = 3)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Quantity")]
        [System.ComponentModel.DataAnnotations.Editable(true, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual int ItemQuantity
        {
            get
            {
                return this.getInteger("ItemQuantity");
            }
            set
            {
                this["ItemQuantity"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Price", Order = 4)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Price")]
        [System.ComponentModel.DataAnnotations.Editable(true, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual decimal Price
        {
            get
            {
                return this.getReal("Price");
            }
            set
            {
                this["Price"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Category", Order = 5)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Category")]
        [System.ComponentModel.DataAnnotations.Editable(false, AllowInitialValue = false)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String ItemCategoryID
        {
            get
            {
                return this.getString("ItemCategoryID");
            }
            set
            {
                this["ItemCategoryID"] = value;
            }
        }

    }
}
