//DO NOT MODIFY THIS FILE
//Instead, override the this[] indexer in your entity base class
using System;
using AppFramework.AppClasses;
namespace FirstAppFrameworkApplicationEntities.EntityClasses
{
    partial class ItemCategory
    {
        [System.ComponentModel.DataAnnotations.Display(Name = "Category ID", Order = 0)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Category ID")]
        [System.ComponentModel.DataAnnotations.Editable(false, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String ItemCategoryID
        {
            get
            {
                return this.getString("ItemCategoryID");
            }
            set
            {
                this["ItemCategoryID"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Quantity", Order = 1)]
        [System.ComponentModel.DataAnnotations.Editable(false, AllowInitialValue = false)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual int ItemQuantity
        {
            get
            {
                return this.getInteger("ItemQuantity");
            }
            set
            {
                this["ItemQuantity"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Category Name", Order = 2)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Category Name")]
        [System.ComponentModel.DataAnnotations.Editable(true, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String ItemCategoryName
        {
            get
            {
                return this.getString("ItemCategoryName");
            }
            set
            {
                this["ItemCategoryName"] = value;
            }
        }

    }
}
