//DO NOT MODIFY THIS FILE
//Instead, override the this[] indexer in your entity base class
using System;
using AppFramework.AppClasses;
namespace FirstAppFrameworkApplicationEntities.EntityClasses
{
    partial class Order
    {
        [System.ComponentModel.DataAnnotations.Display(Name = "Order ID", Order = 0)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Order ID")]
        [System.ComponentModel.DataAnnotations.Editable(false, AllowInitialValue = false)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String OrderID
        {
            get
            {
                return this.getString("OrderID");
            }
            set
            {
                this["OrderID"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Customer", Order = 1)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Customer")]
        [System.ComponentModel.DataAnnotations.Editable(false, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String CustomerID
        {
            get
            {
                return this.getString("CustomerID");
            }
            set
            {
                this["CustomerID"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Order Status", Order = 2)]
        [System.ComponentModel.DataAnnotations.Editable(false, AllowInitialValue = false)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual FirstAppFrameworkApplicationEntities.EDTs.OrderStatus OrderStatus
        {
            get
            {
                return (FirstAppFrameworkApplicationEntities.EDTs.OrderStatus)this.getEnum("OrderStatus");
            }
            set
            {
                this["OrderStatus"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Amount", Order = 3)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Amount")]
        [System.ComponentModel.DataAnnotations.Editable(false, AllowInitialValue = false)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual decimal Amount
        {
            get
            {
                return this.getReal("Amount");
            }
            set
            {
                this["Amount"] = value;
            }
        }

    }
}
