//DO NOT MODIFY THIS FILE
//Instead, override the this[] indexer in your entity base class
using System;
using AppFramework.AppClasses;
namespace FirstAppFrameworkApplicationEntities.EntityClasses
{
    partial class Total
    {
        [System.ComponentModel.DataAnnotations.Display(Name = "Order ID", Order = 0)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Order ID")]
        [System.ComponentModel.DataAnnotations.Editable(false, AllowInitialValue = false)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String OrderID
        {
            get
            {
                return this.getString("OrderID");
            }
            set
            {
                this["OrderID"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Short Description", Order = 1)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Short Description")]
        [System.ComponentModel.DataAnnotations.Editable(false, AllowInitialValue = false)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String Description
        {
            get
            {
                return this.getString("Description");
            }
            set
            {
                this["Description"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Amount", Order = 2)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Amount")]
        [System.ComponentModel.DataAnnotations.Editable(false, AllowInitialValue = false)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual decimal Amount
        {
            get
            {
                return this.getReal("Amount");
            }
            set
            {
                this["Amount"] = value;
            }
        }

    }
}
